# Generated by Django 5.2.5 on 2025-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pizza_options_pizza_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
