# Generated by Django 5.2.5 on 2025-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pizza_slug_alter_pizza_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True, verbose_name='URL slug'),
        ),
    ]
