# Generated by Django 5.2.5 on 2025-08-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pizza_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'ingrédient")),
                ('allergens', models.CharField(blank=True, help_text='Allergènes séparés par des virgules (ex: gluten, lactose, noix)', max_length=200, verbose_name='Allergènes')),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100, verbose_name='Auteur')),
                ('texte', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.pizza', verbose_name='Pizza')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez les ingrédients de cette pizza', to='core.ingredient', verbose_name='Ingrédients'),
        ),
    ]
