# Generated by Django 5.1.2 on 2025-08-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème')),
                ('auteur', models.CharField(max_length=200, verbose_name='Auteur')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note (1-5)')),
                ('disponibilite', models.BooleanField(default=True, verbose_name='Disponibilité')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('age', models.IntegerField(verbose_name='Âge')),
                ('lieu_residence', models.CharField(max_length=200, verbose_name='Lieu de résidence')),
                ('livre_emprunte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunteur', to='gestion.livre', verbose_name='Livre emprunté')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
    ]
